### PR TITLE
v1.0: Push GA by 2 days

### PR DESCRIPTION
**Pull request by fabiand**
… in order to reflect the holidays in some countries

### CODE REVIEW

**Comment by fabiand** [comment]
@rthallisey @aburdenthehand wdyt?

**Comment by aburdenthehand** [comment]
I am ambivalent. I would prefer not to move the release date if we can help it. But if we need people for the release who would otherwise be on holiday then this makes perfect sense.

**Comment by rthallisey** [comment]
Let's discuss more on Wednesday

**Comment by aburdenthehand** [comment]
I believe the Czech Republic also has public holidays on 5th and 6th, and it seems some of our US folks will be out for much of that week. In light of this, I think pushing it a week (July 11th) is better than two days.

**Comment by davidvossel** [comment]
5th or 6th is fine, i'll be available then to cut the release at least.

**Review by davidvossel — COMMENTED** [review]
/lgtm

i will be here on the 6th to coordinate the release.

**Pull request closed without merging**
