### PR TITLE
Postpone 1.3 release

### PR DESCRIPTION
**Pull request by xpivarc**
There were couple of metrics related bugs
that landed only after RC1. It also appears
that we have a small problem in release tool.
Therefore postpone 1.3 to fine tune and solve
these issues.

### CODE REVIEW

**Comment by xpivarc** [comment]
@aburdenthehand @fabiand

**Comment by aburdenthehand** [comment]
/approve 
/hold
(to give others a chance to respond)
Seems reasonable, and I don't see any issues with the proposed date. Thanks @xpivarc.
FYI @rthallisey @vasiliy-ul

**Comment by aburdenthehand** [comment]
@xpivarc are we still tracking for release tomorrow?

**Comment by xpivarc** [comment]
> @xpivarc are we still tracking for release tomorrow?

There is slight delay on my side.

**Comment by xpivarc** [comment]
@aburdenthehand We have rc2 today. Do we want to promote this right away or do we want to wait for a week as we usually do?

**Comment by aburdenthehand** [comment]
@xpivarc let's do as we should and wait a week to ensure quality. Can you please update the schedule?
I am in no rush; my interest is purely for communicating the right date and making sure everything goes out as it should. Thank you!

**Comment by xpivarc** [comment]
> @xpivarc let's do as we should and wait a week to ensure quality. Can you please update the schedule? I am in no rush; my interest is purely for communicating the right date and making sure everything goes out as it should. Thank you!

PTAL

**Pull request merged**
