### PR TITLE
Publish KubeVirt V1 Release Schedule

### PR DESCRIPTION
**Pull request by rthallisey**
Schedule for V1 release.

### CODE REVIEW

**Review by aburdenthehand — APPROVED** [review]
I think I'd prefer a file structure more like:
`sig-release/releases/v1.0/`
I don't think this needs to block this PR though as it's better to have a published schedule

**Comment by rthallisey** [comment]
Not a problem.  Updated.

**Comment by dhiller** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: _[dhiller](https://github.com/kubevirt/sig-release/pull/1#issuecomment-1488319779)_
> 
> The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=kubevirt%2Fsig-release).
> 
> Needs approval from an approver in each of these files:
> * **[OWNERS](https://github.com/kubevirt/sig-release/blob/main/OWNERS)**
> 
> Approvers can indicate their approval by writing `/approve` in a comment Approvers can cancel approval by writing `/approve cancel` in a comment

Ah, looks like we need an OWNERS file here.

**Review by dhiller — APPROVED** [review]

**Pull request merged**
