### PR TITLE
Publish v1.3 release

### PR DESCRIPTION
**Pull request by xpivarc**

### CODE REVIEW

**Comment by aburdenthehand** [comment]
Thanks @xpivarc 
Is there a reason why we've moved from Tuesdays to Wednesdays for most of these?

**Comment by aburdenthehand** [comment]
Looks fine to me. The only issue I would raise is the FF falls on Shavuot for our folks in Israel.
re: Wednesdays, I'm guessing it is trailing the 1.30 release which falls on a Wednesday.

**Comment by xpivarc** [comment]
> Looks fine to me. The only issue I would raise is the FF falls on Shavuot for our folks in Israel. re: Wednesdays, I'm guessing it is trailing the 1.30 release which falls on a Wednesday.

I think having the FF on any holiday isn't bad in nature as on that day you can't do much. You would need to get reviews and pray to CI that it gets merged. Let me know if you want to move it.

We use Wednesday because we trail the release of 1.30.

**Comment by aburdenthehand** [comment]
/approve
@xpivarc Alrighty, sounds good. Thank you

**Pull request merged**
